<?php

namespace Tests\Feature;

use App\Models\Employee;
use App\Models\User;
use Tests\TestCase;

class EmployeeControllerTest extends TestCase
{
    private $adminUser;

    public  function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->adminUser = User::factory()->create(['name' => 'adminTest']);
        $this->actingAs($this->adminUser);
    }

    public function test_employee_create_with_no_company()
    {
        $employee = Employee::factory()->make(['company_id' => null]);
        $response = $this->post(route('employees.store'), $employee->toArray());
        $response->assertStatus(302);
    }

    public function test_employee_create_with_no_email()
    {
        $employee = Employee::factory()->make(['email' => null]);
        $response = $this->post(route('employees.store'), $employee->toArray());
        $response->assertStatus(302);
    }

}
